void welcome();
int user_type();
int regs();
int land(int user_type);
int stu_land();
int teach_land();
int admin_land();
void exit_system();
void student();
void teacher();
void administrator();
int stu_menu();
void stu_modify();
void stu_search_grade();
void stu_display_course();
void stu_display_teacher();
int package_search(long package_num);
int teach_menu();
void teach_add();
void pac_modify(); 
void teach_display_student();
void teach_display_course();
void teach_change_grade();
int teach_search(long teach_num);
int admin_menu();
void manage_student(); 
void manage_package();
void manage_course();
void add_student();
void add_package();
void add_course();
void dele_student();
void dele_teacher();
void dele_course();
void display_all_student();
void display_all_package();
void display_all_course();
void modify_course();

int course_search(long num,int flag);
int select_search(long stu_num,long course_num);
void Load_student_information(char *file_name);
void Load_package_information(char *file_name); 
void save_student_information(char *file_name);
void save_package_information(char *file_name);
